### ISSUE TITLE
Add hyperfoil to kuadrant overlay

### ISSUE THREAD

**Issue by azgabur** [3scale-qe/tools#35]
https://hyperfoil.io/
Hyperfoil operator can be found in OperatorHub
Needed for performance tests

This should be the Hyperfoil CR used. Version "0.26-SNAPSHOT" is important because "latest" does not work with Kuadrant testsuite and http route because mostly missing valid certificates on our clusters.
```yaml
kind: Hyperfoil
apiVersion: hyperfoil.io/v1alpha2
metadata:
  name: hyperfoil
spec:
  version: "0.26-SNAPSHOT"
  route:
    type: "http"
```
